name: flightmobileweb
description: Flight search and booking application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^1.0.0
  cupertino_icons: ^0.1.3
  numeric_keyboard: ^1.0.0
  firebase_core: 0.5.0
  localstorage: ^3.0.2+5
  #firebase_auth: ^0.18.1+1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0
  provider: ^4.3.2+2
  flutter_ticket_widget: ^0.0.1
  flutter_braintree: ^1.1.0
  rflutter_alert: ^1.1.0
  searchable_dropdown: ^1.1.3
  intl: ^0.16.1
#  flutter_facebook_login: ^3.0.0
#  google_sign_in: ^4.5.3
#  firebase_auth: ^0.18.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: WorkSans-Italic-VariableFont_wght
      fonts:
        - asset: fonts/WorkSans-Italic-VariableFont_wght.ttf

#WorkSans-Italic-VariableFont_wght